language: objective-c
osx_image: xcode8.2
xcode_workspace: Library/XZDataLayerViewer.xcworkspace # path to your xcodeproj folder
xcode_scheme: XZDataLayerViewer
podfile: Library/Podfile
script:   
  - xcodebuild  -workspace Library/XZDataLayerViewer.xcworkspace -scheme XZDataLayerViewer -configuration Release -sdk iphonesimulator 
    -destination 'platform=iOS Simulator,name=iPhone 5,OS=8.1' 
    -destination 'platform=iOS Simulator,name=iPhone 5,OS=9.0'
    -destination 'platform=iOS Simulator,name=iPhone 5,OS=10.0'
    -destination 'platform=iOS Simulator,name=iPhone 5,OS=10.1'
    test ENABLE_NS_ASSERTIONS=YES ONLY_ACTIVE_ARCH=NO | xcpretty